//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemBoot.DataAccess.Sqlite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlStatements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlStatements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MemBoot.DataAccess.Sqlite.SqlStatements", typeof(SqlStatements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- The database may contain decks with the same name and description; ID keeps them apart.
        ///
        ///CREATE TABLE IF NOT EXISTS &quot;decks&quot; (
        ///	&quot;sort_id&quot; INTEGER PRIMARY KEY AUTOINCREMENT,
        ///	&quot;id&quot;	BLOB NOT NULL UNIQUE,
        ///	&quot;name&quot;	TEXT NOT NULL,
        ///	&quot;description&quot;	TEXT NOT NULL
        ///);
        ///
        ///-- All fields (used by facts) in a deck must have unique names,
        ///-- but different decks may each contain a field with the same name.
        ///
        ///CREATE TABLE IF NOT EXISTS &quot;fields&quot; (
        ///	&quot;sort_id&quot; INTEGER PRIMARY KEY AUTOINCREMENT,
        ///	&quot;deck_id&quot;	BLOB NOT NU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateAllTables {
            get {
                return ResourceManager.GetString("CreateAllTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS mastery_records;
        ///DROP TABLE IF EXISTS resources;
        ///DROP TABLE IF EXISTS cardtypes;
        ///DROP TABLE IF EXISTS facts_contents;
        ///DROP TABLE IF EXISTS facts;
        ///DROP TABLE IF EXISTS fields;
        ///DROP TABLE IF EXISTS decks;.
        /// </summary>
        internal static string DropAllTables {
            get {
                return ResourceManager.GetString("DropAllTables", resourceCulture);
            }
        }
    }
}
